// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_defectdojo

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func DefectdojoProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type DefectdojoModel struct {
}
